const nombresPersonalizados = {
    "Can add log entry": "Agregar registro",
    "Can change log entry": "Editar registro",
    "Can delete log entry": "Eliminar registro",
    "Can view log entry": "Ver registro",
    "Can add group": "Agregar grupo",
    "Can change group": "Editar grupo",
    "Can delete group": "Eliminar grupo",
    "Can view group": "Ver grupo",
    "Can add permission": "Agregar permiso",
    "Can change permission": "Editar permiso",
    "Can delete permission": "Eliminar permiso",
    "Can view permission": "Ver permiso",
    "Can add content type": "Agregar tipo de contenido",
    "Can change content type": "Editar tipo de contenido",
    "Can delete content type": "Eliminar tipo de contenido",
    "Can view content type": "Ver tipo de contenido",
    "Can add categoria": "Agregar categoría",
    "Can change categoria": "Editar categoría",
    "Can delete categoria": "Eliminar categoría",
    "Can view categoria": "Ver categoría",
    "Can add Color": "Agregar color",
    "Can change Color": "Editar color",
    "Can delete Color": "Eliminar color",
    "Can view Color": "Ver color",
    "Can add Descripción": "Agregar descripción",
    "Can change Descripción": "Editar descripción",
    "Can delete Descripción": "Eliminar descripción",
    "Can view Descripción": "Ver descripción",
    "Can add Descripción de prenda": "Agregar descripción de prenda",
    "Can change Descripción de prenda": "Editar descripción de prenda",
    "Can delete Descripción de prenda": "Eliminar descripción de prenda",
    "Can view Descripción de prenda": "Ver descripción de prenda",
    "Can add imagen prenda": "Agregar imagen de prenda",
    "Can change imagen prenda": "Editar imagen de prenda",
    "Can delete imagen prenda": "Eliminar imagen de prenda",
    "Can view imagen prenda": "Ver imagen de prenda",
    "Can add Notificación": "Agregar notificación",
    "Can change Notificación": "Editar notificación",
    "Can delete Notificación": "Eliminar notificación",
    "Can view Notificación": "Ver notificación",
    "Can add Pregunta": "Agregar pregunta",
    "Can change Pregunta": "Editar pregunta",
    "Can delete Pregunta": "Eliminar pregunta",
    "Can view Pregunta": "Ver pregunta",
    "Can add prenda": "Agregar prenda",
    "Can change prenda": "Editar prenda",
    "Can delete prenda": "Eliminar prenda",
    "Can view prenda": "Ver prenda",
    "Can add prenda color": "Agregar color a prenda",
    "Can change prenda color": "Editar color de prenda",
    "Can delete prenda color": "Eliminar color de prenda",
    "Can view prenda color": "Ver color de prenda",
    "Can add prenda talla": "Agregar talla a prenda",
    "Can change prenda talla": "Editar talla de prenda",
    "Can delete prenda talla": "Eliminar talla de prenda",
    "Can view prenda talla": "Ver talla de prenda",
    "Can add Color por Talla": "Agregar color por talla",
    "Can change Color por Talla": "Editar color por talla",
    "Can delete Color por Talla": "Eliminar color por talla",
    "Can view Color por Talla": "Ver color por talla",
    "Can add talla": "Agregar talla",
    "Can change talla": "Editar talla",
    "Can delete talla": "Eliminar talla",
    "Can view talla": "Ver talla",
    "Can add session": "Agregar sesión",
    "Can change session": "Editar sesión",
    "Can delete session": "Eliminar sesión",
    "Can view session": "Ver sesión",
    "Can add user": "Agregar usuario",
    "Can change user": "Editar usuario",
    "Can delete user": "Eliminar usuario",
    "Can view user": "Ver usuario",
  };
export default nombresPersonalizados;